# -*- coding: utf-8 -*-
"""Lab09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tCtt0Bx7HperT2R209NpEl1tTt8qX0JZ

**Problem 1**
"""

from google.colab import files
uploaded = files.upload()

import numpy as np
import pandas as pd

import io
df = pd.read_csv(io.BytesIO(uploaded['diabetes.csv']))

print(df.describe())

print(df.isnull().sum())

Y = df['Outcome']
df.drop('Outcome',axis=1,inplace=True)
X = df

Y = Y.to_numpy()
X = X.to_numpy()
print(X.shape,Y.shape)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,Y,test_size=0.3, random_state=12)
print(x_train.shape,x_test.shape)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

scaler.fit(x_train)
x_train_std = scaler.transform(x_train)
x_test_std = scaler.transform(x_test)

from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(C=100.0, max_iter=1000)

clf.fit(x_train_std,y_train)

from sklearn.metrics import accuracy_score, confusion_matrix

y_train_pred = clf.predict(x_train_std)

print('Accuracy Score on training data: ',accuracy_score(y_train,y_train_pred))
print(confusion_matrix(y_train,y_train_pred))

y_test_pred = clf.predict(x_test_std)

print('Accuracy Score on testing data: ',accuracy_score(y_test,y_test_pred))
print(confusion_matrix(y_test,y_test_pred))

"""**Problem 2**"""

from sklearn.datasets import load_iris
iris = load_iris()

x = iris.data
y = iris.target
print(x.shape,y.shape)

xtrain, xtest, ytrain,ytest = train_test_split(x,y,test_size=0.2, random_state=42)
print(xtrain.shape,xtest.shape)

scaler.fit(xtrain)
xtrain_std = scaler.transform(xtrain)
xtest_std = scaler.transform(xtest)

clf2 = LogisticRegression(multi_class="ovr")

clf2.fit(xtrain_std,ytrain)

ytrain_pred = clf2.predict(xtrain_std)

print('Accuracy Score on training data: ',accuracy_score(ytrain,ytrain_pred))
print(confusion_matrix(ytrain,ytrain_pred))

ytest_pred = clf2.predict(xtest_std)

print('Accuracy Score on testing data: ',accuracy_score(ytest,ytest_pred))
print(confusion_matrix(ytest,ytest_pred))